### ISSUE TITLE
Some help with game assets

### ISSUE THREAD

**Issue by 4val0v** [ua2004/Millionaire-3D#1]
**Какие-то сорцы**: http://www.sourcecodester.com/6446/who-wants-be-millionaire.html
https://www.planet-source-code.com/vb/scripts/ShowCode.asp?txtCodeId=3013&lngWId=3
https://github.com/aaronnech/Who-Wants-to-Be-a-Millionaire
http://infopolicy.narod.ru/html/cod.html

**По поводу графики**:
очень много нужной графики здесь - http://gameshows.ru/forum/kto-hochet-stat-millionerom-t153.html (Смотри все страницы)

_Также если есть какой-то донор с хорошей графикой, дай ссылку, вытяну тебе ее !_

Также хотел спросить, как реализованы вопросы ответы ?
Хочется что то типа такого - http://forum.unity3d.com/threads/how-i-build-a-who-wants-to-be-a-millionaire-style-quiz-game.282925/#post-1876193
Чтобы ответы могли меняться местами, то-есть одну игру ответ нужный под "A", во второй игру он уже под "C"

> И еще вопрос, можно ли данный проект свободно использовать (Совсем другой смысл игры будет), как заготовку ?

**Comment by ua2004** [comment]
@4val0v, I will write in English so that others could understand.
> По поводу графики

Thank you. I know about that website and if something particular is needed I will ask you)

> Также хотел спросить, как реализованы вопросы ответы ?

Question database is not in XML format. It is stored as SQLite database. You will need a special software to edit it, e.g., [SQLite Browser](http://sqlitebrowser.org/). However, we are planning to encrypt the database in the future so that nobody could view or edit it. Questions will be updated automatically via Internet.

> Чтобы ответы могли меняться местами, то-есть одну игру ответ нужный под "A", во второй игру он уже под "C"

Answers in question are not shuffled at the moment but, of course, they are going to be. It is very easy to obtain.

> И еще вопрос, можно ли данный проект свободно использовать (Совсем другой смысл игры будет), как заготовку ?

Yes, of course. This project is under [GNU General Public License v2](https://github.com/ua2004/Millionaire-3D/blob/master/LICENSE), which means you are free to copy and modify this software as long as it remains free and open source.
